Finish commit
sergeynakul/codebreaker pull request #1
Opened 2020-07-04 10:13 UTC by sergeynakul

2020-07-04 19:26 UTC, dkischenko requested changes

2020-07-04 19:26 UTC, dkischenko commented on Gemfile
> +gem 'rspec', '~> 3.0'
please move all gems to *.gemspec

2020-07-15 17:09 UTC, dmitrybereza requested changes

2020-07-15 17:09 UTC, dmitrybereza commented on .rubocop.yml
> +  Max: 12
pls remove it and rewrite method in 10 lines

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker.rb
> +  require 'errors/inclusion_error'
remove it to autoload.rb, please

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/codemaker.rb
> +    def generate_secret_code(amout = AMOUNT_OF_NUMBERS, range = RANGE_OF_NUMBERS)
maybe better to make this method private, and call him in initializer

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/codemaker.rb
> +    def check(guess_array, secret_code_array)
if i think correctly, its a method which chek user, guess, please create CodeMatcher class, and write this method in CodeMatcher

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/codemaker.rb
> +      @secret_code = ''
secret code = generate_secret_code(......)

private 

def generate_secret_code
....
end

2020-07-15 17:09 UTC, dmitrybereza commented on lib/files/rules.txt
> +Game Rules
remove it to codebreaker_console with I18n gem

2020-07-15 17:09 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +  module ClassMethods
move it to different files, please

2020-07-15 17:09 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +      return unless value.to_s.split('').map(&:to_i).any? { |number| !range.include?(number) }
move valdations to methods, and inside of that method only raise Error

2020-07-15 17:09 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +
raise WrongRangeError unless range_valid?

2020-07-15 17:09 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +    end
same as above

2020-07-15 17:09 UTC, dmitrybereza commented on lib/errors/validation_error.rb
> +end
add initializer with error message

2020-07-15 17:09 UTC, dmitrybereza commented on lib/errors/presence_error.rb
> +class PresenceError < ValidationError
same as below

2020-07-15 17:09 UTC, dmitrybereza commented on lib/errors/out_of_range_error.rb
> +end
same as below

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/guess.rb
> +    validate :numbers, :presence
maybe validate only when we initialize object?

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/game.rb
> +
Please use PRIVATE methods, cuz you write only public methods in whole project

2020-07-15 17:09 UTC, dmitrybereza commented on lib/codebreaker/game.rb
> +    def save_result
move functions which work with files to class

2020-07-15 17:09 UTC, dmitrybereza commented on spec/codebreaker/codemaker_spec.rb
> +module Codebreaker
remove module from specs

2020-07-15 17:09 UTC, dmitrybereza commented on spec/codebreaker/codemaker_spec.rb
> +require 'spec_helper'
remove redundant

2020-07-15 17:09 UTC, dmitrybereza commented on spec/codebreaker/game_spec.rb
>  require 'spec_helper'
remove, and add file .spec

2020-07-15 17:09 UTC, dmitrybereza commented on spec/spec_helper.rb
> +SimpleCov.start
please add branch coverage

2020-07-17 20:18 UTC, pavlo-developer requested changes

2020-07-17 20:18 UTC, pavlo-developer commented on .rubocop.yml
> +  Enabled: false
We were not allowed to turn off this check

2020-07-17 20:18 UTC, pavlo-developer commented on lib/codebreaker/game.rb
> +    end
It seems that this code prohibits returning two hints with the same values, even if the same digit appears in the secret code several times.

My assumption is further supported by the fact that the tests have a "not return the same number" check.

The "hint" method should be able to return the same value many times, of course, only as many times as the number appears in the secret code.

2020-07-17 20:18 UTC, pavlo-developer commented on lib/codebreaker/game.rb
> +    validate :difficulty, :inclusion, %i[easy medium hell]
"`%i[easy medium hell]`" is a duplication of the configuration values described above.

This should be calculated dynamically from the values of the constant.

2020-07-17 20:18 UTC, pavlo-developer commented on lib/codebreaker.rb
> +AMOUNT_OF_NUMBERS = 4
These constants must be in the class they belong to

2020-07-17 20:18 UTC, pavlo-developer commented on lib/codebreaker.rb
> +DIFF_ARRAY = %w[hell medium easy].freeze
Duplication of the values of the constant in which the types of difficulties are listed.

These values should be calculated dynamically based on the values of the constant

2020-07-17 20:18 UTC, pavlo-developer commented on lib/codebreaker.rb
> +RULES_FILE = 'lib/files/rules.txt'
This constant is not used in the gem, and the file it refers to is not related to the gem but to the console application.

2020-07-17 20:18 UTC, pavlo-developer commented on .fasterer.yml
> +  each_with_index_vs_while: false
We are not allowed to turn off this check.
Refactor the code so that the code meets the requirements of the "fasterer".

2020-07-17 20:18 UTC, pavlo-developer commented on .fasterer.yml
> +exclude_paths:
This configuration file should also contain a listing of the checks involved, as described in the instructions for the gem.

2020-07-18 06:23 UTC, sergeynakul commented on lib/codebreaker.rb
> +  require 'errors/inclusion_error'
why not in lib/codebreaker.rb ? Popular gems require files in this directory, for example, Sidekiq

2020-07-18 06:24 UTC, sergeynakul commented on .rubocop.yml
> +  Max: 12
ok, thanks

2020-07-18 06:43 UTC, sergeynakul commented on lib/codebreaker/codemaker.rb
> +    def generate_secret_code(amout = AMOUNT_OF_NUMBERS, range = RANGE_OF_NUMBERS)
not work for me. Can you give an example pseudo-code, please?

2020-07-18 06:45 UTC, sergeynakul commented on lib/codebreaker/codemaker.rb
> +    def check(guess_array, secret_code_array)
ok, thanks

2020-07-18 06:48 UTC, sergeynakul commented on lib/codebreaker/codemaker.rb
> +      @secret_code = ''
not work

2020-07-18 06:51 UTC, sergeynakul commented on lib/files/rules.txt
> +Game Rules
why?

2020-07-18 06:52 UTC, sergeynakul commented on lib/moduls/validations.rb
> +  module ClassMethods
why?

2020-07-18 06:55 UTC, sergeynakul commented on lib/moduls/validations.rb
> +      return unless value.to_s.split('').map(&:to_i).any? { |number| !range.include?(number) }
I don't understand, please explain

2020-07-18 06:56 UTC, sergeynakul commented on lib/moduls/validations.rb
> +
ok. thanks

2020-07-18 07:02 UTC, sergeynakul commented on lib/errors/validation_error.rb
> +end
for what? error message return when raise error in lib/moduls/validations.rb

2020-07-18 07:05 UTC, sergeynakul commented on lib/codebreaker/guess.rb
> +    validate :numbers, :presence
So it is now, 'validate :numbers, :presence' only add validation

2020-07-18 07:06 UTC, sergeynakul commented on lib/codebreaker/game.rb
> +
ok thanks, I think about this

2020-07-18 07:09 UTC, sergeynakul commented on lib/codebreaker/game.rb
> +    def save_result
why? I have class Game, and method save_result which belongs to the game

2020-07-18 07:11 UTC, sergeynakul commented on spec/codebreaker/codemaker_spec.rb
> +module Codebreaker
uninitialized constant Codemaker, if I remove

2020-07-18 07:14 UTC, sergeynakul commented on spec/codebreaker/codemaker_spec.rb
> +require 'spec_helper'
thanks

2020-07-18 07:19 UTC, sergeynakul commented on .rubocop.yml
> +  Enabled: false
why we cannot turn off Style/Documentation ? And what we can turn off?

2020-07-18 07:31 UTC, sergeynakul commented on lib/codebreaker/game.rb
> +    end
you are wrong, please double-check

2020-07-18 07:33 UTC, sergeynakul commented on lib/codebreaker/game.rb
> +    validate :difficulty, :inclusion, %i[easy medium hell]
good idea, thanks!

2020-07-18 07:35 UTC, sergeynakul commented on lib/codebreaker.rb
> +AMOUNT_OF_NUMBERS = 4
These constants I use in two classes. What in this case?

2020-07-18 07:39 UTC, sergeynakul commented on lib/codebreaker.rb
> +DIFF_ARRAY = %w[hell medium easy].freeze
Ok, thank this must be in console. I remove it

2020-07-18 07:41 UTC, sergeynakul commented on .fasterer.yml
> +  each_with_index_vs_while: false
Why not?

2020-07-18 07:46 UTC, sergeynakul commented on .fasterer.yml
> +exclude_paths:
Do you write about example? It is the only example, you can config by yourself.
What checks should I put in the .fasterer.yml and why?

2020-07-18 11:10 UTC, sergeynakul commented on .fasterer.yml
> +  each_with_index_vs_while: false
and in your gem https://github.com/pavlo-developer/GameGemCodebreaker-3/pull/1/files you include each_with_index_vs_while: false to .fasterer.yml

2020-07-18 11:56 UTC, dmitrybereza commented on lib/codebreaker.rb
> +  require 'errors/inclusion_error'
i wrote it because, mentors said about that

2020-07-18 11:57 UTC, dmitrybereza commented on lib/files/rules.txt
> +Game Rules
On public review said about that

2020-07-18 11:57 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +  module ClassMethods
On public review Denis said that we need to write 1 module/class in one file

2020-07-18 11:59 UTC, dmitrybereza commented on lib/moduls/validations.rb
> +      return unless value.to_s.split('').map(&:to_i).any? { |number| !range.include?(number) }
def validate_range(value, name, range)
raise WrongRangeError unless valid_range?(value, name, range)
end

def valid range?(value, name, range)
value.to_s.split('').map(&:to_i).any? { |number| !range.include?(number) }
end

2020-07-18 12:00 UTC, dmitrybereza commented on lib/errors/validation_error.rb
> +end
mentors sais its better to initialize messages in errors constructors

2020-07-18 12:01 UTC, dmitrybereza commented on lib/codebreaker/game.rb
> +    def save_result
methods whitch works with files are not the Game methods

2020-07-18 12:03 UTC, dmitrybereza commented on spec/codebreaker/codemaker_spec.rb
> +module Codebreaker
make in your terminal rspec --init
its creating .spec file with folloing text --require spec_helper, and this line will be redundant

2020-07-18 13:42 UTC, pavlo-developer commented on .rubocop.yml
> +  Enabled: false
From the categories that disable checks and weakening checks, only these configs are:
```
Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe']
```

2020-07-18 13:50 UTC, sergeynakul commented on spec/codebreaker/codemaker_spec.rb
> +module Codebreaker
I already have this file with the following text...

2020-07-18 13:50 UTC, sergeynakul commented on spec/codebreaker/game_spec.rb
>  require 'spec_helper'
ok I will remove, but file .spec I already have

2020-07-18 13:52 UTC, pavlo-developer commented on .fasterer.yml
> +  each_with_index_vs_while: false
This is my mistake. This setting is not specifically disabled, but simply copied from the fasterer's documentation.
Thanks for pointing out this issue. I changed the setting in my code (I'll commit a bit later).

You most likely applied this setting on purpose, so the comment remains valid.

2020-07-18 14:03 UTC, pavlo-developer commented on .fasterer.yml
> +  each_with_index_vs_while: false
And you can't turn it off on purpose because you need the code to meet the requirements of the fasterer. 
We were not allowed to turn off any of the fasterer settings.

2020-07-18 15:07 UTC, pavlo-developer commented on lib/codebreaker/game.rb
> +    end
Yes I was wrong, sorry

2020-07-18 15:17 UTC, pavlo-developer commented on lib/codebreaker.rb
> +AMOUNT_OF_NUMBERS = 4
Perhaps you can put it in "Codemaker".
Denis said on the code review that the constants should be classes of the corresponding entities, and here they are in the root file.
Get constants from another class by full name

2020-07-18 15:24 UTC, pavlo-developer requested changes

2020-07-18 15:24 UTC, pavlo-developer commented on lib/codebreaker.rb
> +RESULTS_FILE = 'lib/files/results_file.csv'
This constant should be in a separate module that deals with the direct work with files.

2020-07-18 15:24 UTC, pavlo-developer commented on lib/codebreaker/game.rb
> +      File.open(RESULTS_FILE, 'a') do |file|
Direct work with files should be placed in a separate module.
This was said during a public review of past homework.

2020-07-25 15:58 UTC, dmitrybereza reviewed
Just change some lets to subject, but now this code looks good

2020-07-25 15:58 UTC, dmitrybereza commented on spec/codebreaker/game_spec.rb
> +    let(:game) { described_class.new(user, :easy, secret_code) }
pls, change it from let to subject

2020-07-25 15:58 UTC, dmitrybereza commented on spec/codebreaker/sorter_spec.rb
> +    let(:sorter) { described_class.new(data) }
same as above

2020-07-25 16:09 UTC, dmitrybereza approved these changes

2020-07-25 20:23 UTC, pavlo-developer requested changes

2020-07-25 20:23 UTC, pavlo-developer commented on lib/codebreaker/sorter.rb
> +    CONDITIONAL_ARRAY = %i[hell medium easy].freeze
These values should be taken from the constant "`DIFFICULTY_HASH`"

2020-07-25 20:23 UTC, pavlo-developer commented on lib/codebreaker/statistic.rb
> +      @file_path = file_path
Where is the value for this variable set?
In the gem code, I did not find a call to this class, and therefore I suspect that the path to the statistics file is passed from the console application (the new version of which is not yet in the repository).

The path to the statistics file should not be passed from the console application, this path must be the value of a constant in this class.

2020-07-25 20:23 UTC, pavlo-developer commented on lib/codebreaker/statistic.rb
> +    end
The logic for working with files must be in a separate module and must be called from this class.

2020-07-25 20:30 UTC, pavlo-developer commented on lib/codebreaker.rb
> +RESULTS_FILE = 'lib/files/results_file.csv'
Here I was wrong. This constant must be in the statistics class.

2020-08-07 17:44 UTC, pavlo-developer requested changes
1. Use "stub" in gem tests in the same way as I described in the comments to the console application.
2. Fix the problems described in the comments to the code, including those that remained after the last review.

Note.
The problems reported as "This issue has not been resolved" are described in the previous comments to the corresponding lines of code.

2020-08-07 17:44 UTC, pavlo-developer commented on lib/codebreaker/statistic.rb
> +    end
This issue has not been resolved

2020-08-07 17:44 UTC, pavlo-developer commented on lib/codebreaker/sorter.rb
> +    CONDITIONAL_ARRAY = %i[hell medium easy].freeze
This issue has not been resolved

2020-08-07 17:44 UTC, pavlo-developer commented on lib/codebreaker/statistic.rb
> +      @file_path = file_path
This issue has not been resolved

2020-08-07 17:44 UTC, pavlo-developer commented on lib/codebreaker/game.rb
> +    end
What happens if this function is called when there are no more hints left?
Add a check and throw an exception if the number of hints available is zero.

2020-08-07 17:44 UTC, pavlo-developer commented on spec/codebreaker/game_spec.rb
> +          { secret_code: 6543, guess: 2222, response: { in_plase: 0, out_of_place: 0 } }
A check for the number of numbers not found should also be.

2020-08-09 17:05 UTC, dmitrybereza commented on lib/codebreaker/game.rb
> +    def any_hints_left?
call this function in take hint pls

2020-09-01 19:33 UTC, merged